services:
  db:
    image: postgres:16-bookworm
    container_name: tododb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres 
    ports:
      - "15432:5432"
    volumes:
      - todo-db-data:/var/lib/postgresql/data
      - ./schemas:/docker-entrypoint-initdb.d

volumes:
  todo-db-data:
