// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package tododb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Todo struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Done        bool
	Createat    time.Time
}
