// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const queryTodos = `-- name: QueryTodos :many
SELECT
 id, name, description, done, createat 
FROM
 todo
ORDER BY name
`

func (q *Queries) QueryTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, queryTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Done,
			&i.Createat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
